name: Unit Tests CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: CMake Configure
      run: mkdir build && cd build && cmake ..

    - name: Compile
      working-directory: ./build/
      run: cmake --build .

    - name: Run Tests
      working-directory: ./test/
      run: ../build/test/libdbc_test

    - name: Upload dbcconvert
      uses: actions/upload-artifact@v4
      with:
        path: ./build/dbcconvert/dbcconvert

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: CMake Configure
      run: mkdir build && cd build && cmake ..

    - name: Compile
      working-directory: ./build/
      run: cmake --build .

    - name: Run Tests
      working-directory: ./test/
      run: ../build/test/debug/libdbc_test

    - name: Upload dbcconvert
      uses: actions/upload-artifact@v4
      with:
        path: ./build/dbcconvert/debug/dbcconvert
